### ISSUE TITLE
Configuration File to scope checks by tag or resource and toggle individual audit checks 

### ISSUE THREAD

**Issue by donbecker** [jonrau1/ElectricEye#40]
**Story**
As a user of ElectricEye, I want to indicate scope in a configurable manner so that I can limit/selectively target resources via tags and/or resource type.

Currently the Python Auditors are separate files uploaded to S3 and to change scope ElectricEye users are instructed to modify the Python Auditor files directly. 

**Definition of Done**
- Default configuration provided
- Documented configuration (examples, etc)
- Support existing ElectricEye deployments (generate default config file if it does not exist?)
- Python Auditors updated to use configuration file
- Configuration is not AWS specific (as it appears ElectricEye plans to expand to non-AWS cloud auditing) 
- Configuration file could be stored in same S3 bucket as Auditors, but suggest a different folder to prevent accidental overwrites when updating Auditor files. 

**Nice to Have**
Taking this idea further, the proposed configuration file could also determine if individual Python Auditor files (and their multiple checks) are to be active/deactive (run/not run). Currently this is achieved by removing those files from the S3 bucket. 

**Additional Information**
As originally suggested here: https://github.com/jonrau1/ElectricEye#7-can-i-scope-these-checks-by-tag-or-by-a-certain-resource

**Comment by donbecker** [comment]
Some questions on the above: 

1. Do we have a preference regarding a config file format? 
AFAIK the two popular options for Python would be [ConfigParser](https://docs.python.org/3/library/configparser.html) and [YAML (PyYAML](https://pyyaml.org/wiki/PyYAML).

2. The existing process of managing the Auditor Python files is manual. If we are introducing the ability to toggle on/off Auditors via a config, it may be helpful to change Auditor file management to just uploading all Auditor files and overwriting any existing. 

3. Since the Auditor files are currently AWS specific, perhaps it would be more straightforward to tie the config file to AWS as well.

**Comment by jodybrazil** [comment]
@donbecker - I like it!  Great suggestions.  Thinking through what a config file could look like, I like the idea of a single config file formatted as yaml with global and check specific configuration settings.  Thinking through your suggestions above, here are my initial thoughts on a config file template:

```
---
global:
  include-tags:
    - key: text # include resources with tag with this key.  If resource doesn't match, the finding will be set to suppressed
      value: text # optionally match on tag value - if provided tag value must match
  exclude-tags: # exclude overrides include.  If a resource has an "include tag" and an "exclude tag", resource will be excluded
    - key: text # exlude resources with tag with this key.  If resource matches, finding will be suppressed
      value: text # optionally match on tag value - if provided tag value must match
  include-checks: # If any checks are listed in the config, only these checks will be run.  If empty, all checks will be run.
    - check-name # string value of check name to include.
    - check-name2
  include-resources: # if any resources are defined, all other resource findings will be marked suppressed.  Default - all resources evaluated
    - resource-arn
  exclude-resources: # any findings will be marked suppressed for excluded resources
    - resource-arn
  exclude-checks: # Exclude will override include if the same check is in both lists
    - check-name3 # excluded checks will not be executed
  include-auditors:
    - auditor-name # only execute specific auditors
  exclude-auditors: # Exclude will override include if the same auditor is in both lists
    - auditor-name # don't run specific auditors
aws:
  checks:
    check-name1:
      inputs: # add support for user-supplied inputs to checks.  For example, password expiration of 30, 60, 90 days versus hard coded in check.
      input-key: value # inputs accepted by a check.
      include-tags: # union of global and check-specific include tags
        - key: text
          value: value
      exclude-tags: # union of global and check-specific exclude tags
        - key: text
          value: value
      include-resources:
        - resource-arn
      exclude-resoruces:
        - resource-arn
      enabled: true # if not enabled, check will not be run.  This overrides global settings
```

**Comment by donbecker** [comment]
@jodybrazil @jonrau1 Great, thanks for the feedback. I'll run with the YAML example above.

**Comment by jonrau1** [comment]
Ideally Id like the YAML config to work like how it does in WhiteSource where you always provide the default but you can edit your own when you run it.

I always wanted ElectricEye (besides the setup) to be one-click and as long as that can be preserved I am super supportive and it is a better approach than my thought of writing the handling into every Auditor

**Comment by donbecker** [comment]
@jonrau1 Regarding one-click I have some additional AWS CLI code I've generated for setup (to avoid console). I'll make that a separate future PR. 

Regarding 'always provide the default' I'll create a default config that includes all that can then be modified. Taking that route means that we'd require the config file be there, correct?

**Comment by jonrau1** [comment]
@donbecker keen on seeing that - I have been meaning to do something similar to get away from the manual-run-once step when using Fargate. Though now that there is CLI support it is a lot less important...

Hmm, I jumped into that too quick that is right, if there was a default config that would break everyone without it. I am wondering if there is a way to generate it or if everyone would have to bump - that would almost warrant a v3.0 unless we could migrate the exceptions to the CLI versus even going with a Config file.

**Comment by donbecker** [comment]
@jonrau1 The simplest solution would be to not require the config file and then default that to "run everything" which is the current behavior. 

I'm currently documenting out the python callstack. Do you have any opinion regarding a debug level log output/method that I could then view in the CloudWatch logs? 

I'm not a Python expert, so if I need to add these to get the config file implemented, I'd prefer to do it in a way that it's reusable for others. There is also the consideration that having some sort of debug for users to verify their configfile is correct in CloudWatch may be useful too.

**Comment by donbecker** [comment]
@jonrau1 

I have the following working: 
- Backwards compatibility: absent/missing config file results in all auditors being run (existing behavior)
- More detailed/verbose logging statements toggled via blank txt files in S3
- Yaml Config file is dynamically parsed and handles lists of specific auditors or wildcards / all auditors of a service (ex: "ec2.*")
- Located a [yaml file validation library](https://pykwalify.readthedocs.io/en/unstable/basics.html) to validate the config file
- Current idea to implement filtering by tags via users placing [Boto3 filters](https://russell.ballestrini.net/filtering-aws-resources-with-boto3/) directly in the yaml config

However, I think I need some input on the approach to filtering by tags. 

Looking over the existing Auditors and the way they leverage Boto3, there appears to be some caching going on inbetween separate checks, is that correct? I saw the notes in the README on throttling, and I'd like to make sure the filtering approach considers this as well. 

For example, consider the following config file: 
```
instancegroup:
  enabled: true
  checks:
    - ec2.public_ami_check
      filters: 
      - "Name:webapp23*"
    - ec2.encrypted_ami_check
      - "Environment:Prod"
```

In the above example, there are two checks that will be run: 
1. ec2.public_ami_check on AMIs where the Name starts with "webapp23"
2. ec2.ebs_volume_attachment_check on all AMIs where the Envrionment tag is "Prod"

In `AMI_Auditor.py`, both of these checks make a call to 'describe_images' to either retrieve the cache from the boto3 client call or to call `ec2.describeimages` if there is no cache. 

Is the best place to filter the Boto3 results in the individual check execution, after it retrieves the cache? 

If we implement global filters (that apply to call checks) should we apply the global filter when we actually call the Boto3 client, which would result in global filter applying to the cache itself? 

The caching for each set of auditors is located inside each auditor file. Would there be any benefit to analyzing all the audit calls in the config file and first calling to fill the cache prior to running the checks? I saw mention of throttling in the README, so I wasn't sure how much of a concern that was. I'm also not 100% on the lifecycle of the cache if the auditor files are called multiple times via the config file.

Is there any value/need here to filter in relation to other resources (example: audit SecurityGroups attached to EC2 instances with a particular tag)? 

Feel free to reel me in here if I'm chasing use cases that aren't likely.
